rest_version.data_model_field.*:
  type: config_entity
  label: 'Data model field config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    field_config:
      type: mapping
